### PR TITLE
Implement cleanup policy

### LINKED ISSUE #63: Allow assigning cleanup policies to repositories
* **What are you trying to do?**
Assign a cleanup policy like described here: https://help.sonatype.com/repomanager3/cleanup-policies

* **What feature or behavior is this required for?**
Remove no longer necessary packages to ease storage requirements

* **How could we solve this issue? (Not knowing is okay!)**
Here is where someone implemented it for the Conan repository type: 
https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/80

### PR DESCRIPTION
**Pull request by ThYpHo0n**
This PR addresses https://github.com/sonatype-nexus-community/nexus-repository-composer/issues/63 and implements the needed changes to assign cleanup policies to Composer repositories. This greatly helps to maintain your Nexus instance to not waste disk space for old/unused artifacts.

I used the referenced PR from the issue pointing to the Conan repo plugin and how they implemented there.

image

It relates to the following issue #s:
* Fixes #63 

I tested it successfully on our own Nexus instance and it cleaned up the artifact as expected.

### CODE REVIEW

**Comment by ThYpHo0n** [comment]
@bhamail any ETA/feedback for this PR to be merged?

**Review by bhamail — APPROVED** [review]
LGTM. I'm no expert, so please verify you're still happy with the changes after my recent merge of the main branch into this PR. If so, I'm ready to push the big read merge button.
(Thanks for the contribution and apologies for the slow response).

**Comment by ThYpHo0n** [comment]
Changes after the merge still look good to me 👍🏻

**Comment by githoober** [comment]
The cleanup task does not find any composer components to remove. I am using Nexus 3.47 and Composer plugin 0.0.29 released on Nov 7, 2022, whereas this PR was merged a month later. Does anyone know when the next version of the plugin will be released?

**Pull request merged**
