### PR TITLE
Package list can be updated for disabled redeploy repositories

### LINKED ISSUE #31: Composer Hosted - New package version not in package JSON ...
I try to add new versions of my package on a hosted composer repo.
New versions don't appear on `https://my.nexus/repository/composer_hosted/p/vendor/package.json` ...
I only have my first package version.

Currently, I push a 1.0.0 version and few minutes after, I push 1.0.1, but json say :

```
{
  "packages": {
    "vendor/package": {
      "1.0.0": {
        "name": "vendor/package",
        "version": "1.0.0",
        "dist": {
          "url": "https://my.nexus/repository/composer_hosted/vendor/package/1.0.0/vendor/package-1.0.0.zip",
          "type": "zip",
          "reference": "xXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx",
          "shasum": "xXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx"
        },
        "time": "2018-10-01T12:39:52+00:00",
        "uid": 3251794098,
        "autoload": {
          "psr-4": {
            "Vendor\\Package\\": "src/"
          }
        },
        "authors": [
          {
            "name": "Me",
            "email": "me@me.me"
          }
        ],
        "description": "My package ..."
      }
    }
  }
}
```

Is anyone have same problem ?

### PR DESCRIPTION
**Pull request by tetram**
This pull request makes the following changes:
* Provider json file is now correctly updated when pushing a new version on a repository with a "disable redeploy" policy

It relates to the following issue #s:
* Fixes #31

### CODE REVIEW

**Comment by tetram** [comment]
Hello,
Is there any reviewer with write access who could have a look at my PR please :) ?

**Comment by tetram** [comment]
Hello,
Could someone review this PR please ?

**Comment by func0der** [comment]
Yeah, this would be great. If this is not an intended feature, we should find a way to handle this somehow differently.

**Comment by autoscatto** [comment]
Please check this pull request

**Review by bhamail — CHANGES_REQUESTED** [review]
I'm no expert on formats, but @DarthHater explained some of what is going on here to me, and I have deluded myself into thinking I have half a clue. That said, I will plan to merge this PR, but please be sure to test the result and report any issues you find.

But first, I pulled this code down and discovered it no longer compiles due to changes in the latest Nexus Repository Manager version. I fixed the compile error with the following import changes. Could you apply these changes to this PR? Then we should get a happy CI build, and I can merge it.
```
Index: nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerWritePolicySelector.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerWritePolicySelector.java	(revision cbcb2404c975ee5aca4d4f71cf31a04c780506d4)
+++ nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerWritePolicySelector.java	(date 1603395936904)
@@ -12,15 +12,15 @@
  */
 package org.sonatype.nexus.repository.composer.internal;
 
+import java.util.Objects;
+
+import org.sonatype.nexus.repository.config.WritePolicy;
 import org.sonatype.nexus.repository.storage.Asset;
-import org.sonatype.nexus.repository.storage.WritePolicy;
 import org.sonatype.nexus.repository.storage.WritePolicySelector;
 
-import java.util.Objects;
-
+import static org.sonatype.nexus.repository.config.WritePolicy.ALLOW;
+import static org.sonatype.nexus.repository.config.WritePolicy.ALLOW_ONCE;
 import static org.sonatype.nexus.repository.storage.AssetEntityAdapter.P_ASSET_KIND;
-import static org.sonatype.nexus.repository.storage.WritePolicy.ALLOW;
-import static org.sonatype.nexus.repository.storage.WritePolicy.ALLOW_ONCE;
 
 public class ComposerWritePolicySelector implements WritePolicySelector {
 
```

@davidferlay 
@autoscatto

**Comment by bhamail** [comment]
Changed my mind. I'm gonna try and get this PR merged first, then fix the compile issue.

**Comment by tetram** [comment]
Nice i'll be able to remove my quite useless fork now :)

Regards

**Pull request merged**
