### PR TITLE
Update to use new version of nexus 3.38+

### PR DESCRIPTION
**Pull request by fghamsary**
As explained in the https://github.com/sonatype-nexus-community/nexus-repository-composer/issues/103 the new version of Nexus have changed SearchFacet and we should use the new version ElasticSearchFacet instead.

This pull request makes the following changes:
* Usage of ElasticSearchFacet instead of SearchFacet

It relates to the following issues:
* [Compatibility with Nexus 3.38.0+](https://github.com/sonatype-nexus-community/nexus-repository-composer/issues/103)

### CODE REVIEW

**Review by jba31 — APPROVED** [review]

**Comment by fghamsary** [comment]
As I didn't have time to check all the other changes, there are tests on Integration tests that are not passing because of configuration, if someone has some idea about the changes, any suggestion would be appritiated.

**Comment by sjweixel** [comment]
The config file looked the same as older config file that passed successfully.  Could you try running the build-and-test again?

**Comment by max464** [comment]
We are also looking forward to this patch.
Guys please repeat test.

**Comment by shirimaasen** [comment]
Can you re-run tests, please?

**Comment by bhamail** [comment]
I just noticed this PR. I had created PR #108, which is similar but instead uses a generic SearchFacet. You might want to try that approach instead of using ElasticSearchFacet. (I'm happy to use this PR instead if that change helps the tests to pass).

**Review by bhamail — APPROVED** [review]
Thanks! FTR, the seemingly unrelated CI changes were done by me in order to debug the IT failures.

**Comment by bhamail** [comment]
Thanks to Dawid for pointing out I should use `org.sonatype.nexus.repository.search.index.SearchIndexFacet` instead of `SearchFacet`. This change has been made on the main branch.

**Pull request merged**
