### PR TITLE
update to build against Nexus Repository Manager 3.38.1

### PR DESCRIPTION
**Pull request by bhamail**
Some changes to build using NXRM 3.38.1

Uses generic SearchFacet (instead of ElasticSearchFacet used in #104).

It relates to the following issue #s:
* Relates to #104 and #100

### CODE REVIEW

**Comment by bhamail** [comment]
Closed. Using PR #104 instead.

**Comment by sjweixel** [comment]
I downloaded nexus-repository-composer-0.0.22-bundle.kar, which seems to contain this fix.  I saved the file to the deploy directory.  In the nexus web interface, create repo shows a list of composer repo types (group, hosted, and proxy), but clicking any of these does not open the configuration screen.   I don't see anything in the logs indicating any errors caused by the composer plugin.  Do you have any suggestions on how to fix?

**Comment by bhamail** [comment]
What version of Nexus are you running?

**Comment by sjweixel** [comment]
3.38.1-01

**Comment by bhamail** [comment]
@sjweixel Interesting. I just downloaded NXRM and unzipped into a new directory, then also downloaded the pre-build 1nexus-repository-composer-0.0.22-bundle.kar` from central and copied the .kar into `nexus-3.38.1-01/deploy/`. I was able to get to the config screen for a composer proxy.  (screenshot below).
Could you try installing the componer .kar in a new Nexus installation? Maybe there is something leftover from prior install attempts?
Screen Shot 2022-05-02 at 4 34 47 PM

**Pull request closed without merging**
