### PR TITLE
Versions corrected and build directory for copy corrected

### PR DESCRIPTION
**Pull request by taz77**
Update the Dockerfile to build correctly. The version of Nexus was updated in the Pom but never in the Dockerfile. Also, the target directory of the build had moved.

This pull request makes the following changes:
* Update Dockerfile to build

### CODE REVIEW

**Comment by taz77** [comment]
Who is a committer for this project that I can tag?

**Comment by aornatovskyy** [comment]
> Who is a committer for this project that I can tag?

@taz77 I'm not a committer but you can tag me. I will try to help if required.

**Review by aornatovskyy — APPROVED** [review]
LGTM

**Comment by bhamail** [comment]
@taz77 I think this commit: https://github.com/sonatype-nexus-community/nexus-repository-composer/commit/5679dcb0b9f739397c37c2fb02bc6a4d960f2b48#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557 solves the issue of stale Nexus versions. Please holler if there is still a problem, and if not can this PR be closed?

Also, apologies for the slow response.

**Pull request closed without merging**
