### PR TITLE
Feature source added via put content

### PR DESCRIPTION
**Pull request by fghamsary**
Added possibility to add source tag in packages.json when uploading a package zip file.

This pull request makes the following changes:
* Adds attributes to the package asset if there are present (src-type, src-url, src-ref)
* Adds possibility to use multipart form PUT to send the meta data (src-type, src-url, src-ref)
* Provides these attributes (src-type, src-url, src-ref) as a source tag in packages json composer endpoint

This is the implementation we are using for the following feature request #55 

Just a single test have been added and it might be better to add still more test.

### CODE REVIEW

**Comment by fghamsary** [comment]
Can anybody check this please?

**Comment by saitho** [comment]
We'd be interested in this feature as well. :+1: 

cc @allenhsieh

**Comment by fghamsary** [comment]
Can somebody please check this or propose another choice?
We have used this version on our production, but I would like to have it in the original package.

**Comment by DarthHater** [comment]
@fghamsary tagging @jlstephens89 to take a gander!

**Comment by fghamsary** [comment]
Just wondering if anybody cares about this?

**Comment by jmalinens** [comment]
any feature is greatly appreciated on nexus composer as many people use it ;)

**Comment by DarthHater** [comment]
@fghamsary @jmalinens I echo that. Trying to get @jlstephens89 to jump in, his team and co own these formats more or less nowadays (@bhamail and I spend a lot less time on them than we used to). I think come April you'll see a bit more traction. If push comes to shove I'll come in and see if I can get this merged!

**Comment by saitho** [comment]
@jlstephens89 Any updates on this one? :)

**Comment by jlstephens89** [comment]
@saitho No updates yet but as a team we're developing a program to get more eyes on these PRs. Watch this space :)

**Review by stefaanneyts — APPROVED** [review]

**Review by stefaanneyts — APPROVED** [review]

**Comment by fghamsary** [comment]
Can anybody with approval access, check this, I've been using my code in production for more than a year now, and everything is working as it should.
I'd be glad to do more changes to my commits, or even add extra functionality to this repository and contribute more, but honestly when I see that a single change like this takes a whole year to be verified, I'm a little disappointed.

**Comment by fghamsary** [comment]
@jlstephens89 @allenhsieh @stefaanneyts Who can do something about it? Is there a problem with the code that I should correct?

**Review by jlstephens89 — APPROVED** [review]
👍 @fghamsary you're absolutely right. Thank you for testing this in your production environment and sorry it has taken us so long to get around to accepting it.

**Pull request merged**
