### PR TITLE
Update to Nexus 3.21.2-03

### PR DESCRIPTION
**Pull request by Sessa93**
This pull request makes the following changes:
* Update dependencies to 3.21.2-03

### CODE REVIEW

**Comment by joedragons** [comment]
Would be nice if the readme was updated too, still says 0.0.2.  No concern besides CLA sign here though.

**Comment by joedragons** [comment]
I'm newer at this, but I'm not clear on why you changed back to 0.0.5.  https://github.com/sonatype-nexus-community/nexus-repository-composer/pull/28 seems to have updated it and it's logical for me that it's done.

Maybe @jlstephens89 or @bhamail have input.

**Comment by aornatovskyy** [comment]
@Sessa93  hi! Do you still need it for 3.21? i going to create for 3.26. Don't you mind I will close it for 3.21?

**Comment by aornatovskyy** [comment]
closing this one because of the latest 3.26.0 was merged #80

**Pull request closed without merging**
